        self.datalist = [
        {"image": os.path.join(dataset_dir,"01-VE.nii.gz"), "label": os.path.join(dataset_dir,"01-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"02-VE.nii.gz"), "label": os.path.join(dataset_dir,"02-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"03-VE.nii.gz"), "label": os.path.join(dataset_dir,"03-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"04-VE.nii.gz"), "label": os.path.join(dataset_dir,"04-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"05-VE.nii.gz"), "label": os.path.join(dataset_dir,"05-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"06-VE.nii.gz"), "label": os.path.join(dataset_dir,"06-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"07-VE.nii.gz"), "label": os.path.join(dataset_dir,"07-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"08-VE.nii.gz"), "label": os.path.join(dataset_dir,"08-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"09-VE.nii.gz"), "label": os.path.join(dataset_dir,"09-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"10-VE.nii.gz"), "label": os.path.join(dataset_dir,"10-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"11-VE.nii.gz"), "label": os.path.join(dataset_dir,"11-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"12-VE.nii.gz"), "label": os.path.join(dataset_dir,"12-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"13-VE.nii.gz"), "label": os.path.join(dataset_dir,"13-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"14-VE.nii.gz"), "label": os.path.join(dataset_dir,"14-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"15-VE.nii.gz"), "label": os.path.join(dataset_dir,"15-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"16-VE.nii.gz"), "label": os.path.join(dataset_dir,"16-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"17-VE.nii.gz"), "label": os.path.join(dataset_dir,"17-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"18-VE.nii.gz"), "label": os.path.join(dataset_dir,"18-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"19-VE.nii.gz"), "label": os.path.join(dataset_dir,"19-VE-"+str(self.anatomy)+".nii.gz")},
        {"image": os.path.join(dataset_dir,"20-VE.nii.gz"), "label": os.path.join(dataset_dir,"20-VE-"+str(self.anatomy)+".nii.gz")}
        ]